---
- name: This playbook installs a package
  hosts: all
  become: true

  tasks: 
  - name: installing a package
    yum: 
      name: ['git', 'make', 'wget', 'mysql', 'tree', 'docker']
      state: present
