---
- name: This playbook installs httpd package
  hosts: all
  become: true

  tasks: 
  - name: installing a package
    yum: 
      name: httpd
      state: installed
    notify: starting httpd service

  handlers:
  - name: starting httpd service
    service:
      name: httpd
      state: started
      
