---
- name: This playbook installs httpd package
  hosts: all
  become: true

  tasks: 
  - name: installing  httpd
    yum: 
      name: httpd
      state: present
    when: ansible_os_family == "RedHat"

  - name: starting service httpd
    service:
      name: httpd
      state: started
    when: ansible_os_family == "RedHat"

  - name: installing apache2
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"

  - name: starting service apache2
    service:
      name: apache2
      state: started
    when: ansible_os_family == "Debian"
