---
- name: setup tomcat
  hosts: all
  become: true

  tasks:
  - name: installing java on RedHat
    yum:
      name: java
      state: installed
    when: ansible_os_family == "RedHat"

  - name: installing java on Debian
    apt:
      name: default-jdk
      state: present
    when: ansible_os_family == "Debian"

  - name: Download Tomcat
    get_url:
      url: https://mirrors.estointernet.in/apache/tomcat/tomcat-8/v8.5.68/bin/apache-tomcat-8.5.68.tar.gz
      dest: /opt


  - name: Extract tomcat package
    unarchive:
      src: /opt/apache-tomcat-8.5.68.tar.gz
      dest: /opt
      remote_src: yes

  - name: executable permissions
    file:
      path: /opt/apache-tomcat-8.5.68/bin/startup.sh
      mode: 0777

  - name: start tomcat service
    shell: nohup ./startup.sh
    args: 
      chdir: /opt/apache-tomcat-8.5.68/bin
    

          
